# darkness_of_my_soul color scheme for alacritty

colors:
  # Default colors
  primary:
    background: '#010409'
    foreground: '#FEFEFA'

    dim_foreground: '#ABADB0'
    bright_foreground: '#ffffff'
    dim_background: '#010409'
    bright_background: '#000000'

  # Normal colors
  normal:
    black: '#010409'
    red: '#F31616'
    green: '#00A676'
    yellow: '#8C552C'
    blue: '#005FA3'
    magenta: '#C69DD2'
    cyan: '#33829D'
    white: '#FEFEFA'

  # Bright colors
  bright:
    black: '#6C6E6F'
    red: '#FAA0A0'
    green: '#30B76D'
    yellow: '#EDF86C'
    blue: '#B0D9FF'
    magenta: '#F9B3D1'
    cyan: '#7AB6CD'
    white: '#ffffff'

  # Dim colors
  dim:
    black: '#000000'
    red: '#F31616'
    green: '#00A676'
    yellow: '#8C552C'
    blue: '#005FA3'
    magenta: '#C69DD2'
    cyan: '#33829D'
    white: '#ABADB0'
